lasers:
  - name: laser_1
    power: 50
  - name: laser_2
    power: 30
    
mirrors:
  - name: mirror_1_VIS
    x_position: 0
    y_position: 0
    affine_matrix_path: /home/eduardo.hirata/repos/coPylot/copylot/assemblies/photom/demo/affine_T.yml
  - name: mirror_2_IR
    x_position: 0
    y_position: 0
    affine_matrix_path: /home/eduardo.hirata/repos/coPylot/copylot/assemblies/photom/demo/affine_T_2.yml
