lasers:
  - name: laser_1
    power: 50
  - name: laser_2
    power: 30
    
mirrors:
  - name: mirror_1_VIS
    COM_port: COM8
    x_position: 0
    y_position: 0
    affine_matrix_path: C:\Users\ZebraPhysics\Documents\GitHub\coPylot\copylot\assemblies\photom\demo\affine_T.yml